### ISSUE TITLE
NWNX .35 Todo/Issues

### ISSUE THREAD

**Issue by Daztek** [nwnxee/unified#1569]
Bunch of stuff to keep track of for .35

**Must Fix Issues**
* [x] Check out NWNX_Damage with regards to custom damage types
* [x] Check out NWNX_Item_GetEntireItemAppearance()'s sprintf since part vars changed in size
* [x] Check out NWNX_Item_SetItemAppearance (Note changes in changelog)
* [x] [Optimizations::ReconcileAutoMap] Account for JsonToObject since that can create areas too
* [x] Add Unyielding effect mask
* [x] Can't hook CNWSTrigger::EventHandler? #1577
* [x] Remove ifdef out'd params from CNetLayerWindow.hpp
* [x] See if `NWNX_ON_CLIENT_SET_DEVICE_PROPERTY_.*` needs changes
* [x] Oopsie, inline VM functions after rebase: https://github.com/nwnxee/unified/commit/6633c8540d620c985fe5f912e8328cc7693be9b8
* [x] Add ELC multiclass check

**To do**
* [x] Update the changelog
* [x] Deprecate a billion things

**Maybe?**
* [ ] Add CNetLayerInternal struct
* [ ] Check out NWNX_ELC (& basegame ELC)
* [ ] Investigate NWNX_Creature_GetIsBartering() returning true when it doesn't make sense to
* [ ] Add walk drive flag (1) to NWNX_ON_INPUT_KEYBOARD_* 
* [ ] Check early bails of NWNX_ON_DO_X_DETECTION: https://github.com/nwnxee/unified/issues/1580
* [x] Update the various num multiclass checks

**Comment by Daztek** [comment]
WIP Changelog:

### Added
- Administration: added `NWNX_ADMINISTRATION_OPTION_SHOW_PLAYER_JOIN_MESSAGES` to {Get|Set}PlayOption.
- Effect: added `NWNX_EFFECT_EXTEND_DURATION_TYPE` which extends ApplyEffectToObject() to apply effects with `DURATION_TYPE_EQUIPPED` and `DURATION_TYPE_INNATE`.
- SQL: added `CHARACTER_SET` support to PostgresSQL.
- Optimizations: added `NWNX_OPTIMIZATIONS_CACHE_DEBUGGER_INSTANCES` to cache nwscript debugger instances, improving GetScriptBacktrace() performance.

##### New NWScript Functions
- Area: SetDefaultObjectUiDiscoveryMask()
- Effect: SetEffectCreator()
- Effect: GetIsEffectValid()
- Effect: GetAppliedEffectCount()
- Effect: GetAppliedEffect()
- Events: UnsubscribeAllStartingWith()
- Object: ForceAssignUUID()
- Player: GetGameObject()
- Player: SetObjectUiDiscoveryMaskOverride()
- SQL: PostgreSQL_SetNextQueryResultsBinaryMode()

### Changed
- SQL: Sqlite support now uses the sqlite3 embedded in NWNX.
- Core: NWScript NWNX Functions are now also blocked in DelayCommand/AssignCommand spawned from script chunks unless disabled by config.
- Item: GetEntireItemAppearance() and RestoreItemAppearance() now support the new extended model part range.

### Removed
- The following tweaks / optimizations have been removed due to being fixed or added in the basegame:
  - `NWNX_TWEAKS_SUMMON_ASSOCIATE_USE_COMPUTE_SAFE_LOCATION`
  - `NWNX_TWEAKS_FIX_DM_FACTION_BUG`
  - `NWNX_TWEAKS_FIX_DM_SELECTION_BOX`
  - `NWNX_TWEAKS_FIX_MULTICLASS_XP_PENALTY_BUG`
  - `NWNX_OPTIMIZATIONS_FIX_PLACEABLE_VFX_REAPPLY_BUG`
  - `NWNX_OPTIMIZATIONS_CLIENT_GAMEOBJECT_UPDATE_TIME` `NWNX_OPTIMIZATIONS_CLIENT_GAMEOBJECT_UPDATE_TIME_LOADING`
  - `NWNX_OPTIMIZATIONS_RECONCILE_AUTOMAP_DATA`
  - `NWNX_OPTIMIZATIONS_UPDATE_LIST_COMPARISONS`
- The following NWNX NWScript functions have been removed due to being implemented in the basegame, see [Compatibility/nwnx_deprecated.nss](Compatibility/nwnx_deprecated.nss) for more information!
  - Creature: GetMemorisedSpellCountByLevel()
  - Creature: GetMemorisedSpell()
  - Creature: SetMemorisedSpell()
  - Creature: GetKnownSpellCount()
  - Creature: GetKnownSpell()
  - Creature: ClearMemorisedKnownSpells()
  - Creature: ClearMemorisedSpell()
  - Creature: {Get|Set}Soundset()
  - Creature: SetGender()
  - Creature: RestoreSpells()
  - Creature: GetDomain()
  - Creature: GetSpecialization()
  - Creature: GetSpellUsesLeft()
  - Creature: GetMemorizedSpellReadyCount()
  - Effect: SetEffectExpiredScript()
  - Effect: GetEffectExpiredData()
  - Effect: GetEffectExpiredCreator()
  - Effect: AccessorizeVisualEffect() 
  - Object: StringToObject()
  - Object: CheckFit()
  - Object: AddIconEffect()
  - Object: RemoveIconEffect()
  - Object: SetFacing()
  - Regex: Search()
  - Regex: Replace()
  - Regex: Match()
  - Util: IsValidResRef()
  - Util: Get2DARowCount()
  - Util: GetNSSContents()
  - Util: GetServerTicksPerSecond()

### Fixed
- Item: SetItemAppearance() now properly works with WeaponColor/Model, identical to CopyItemAndModify()
